In [ ]:
pip install --upgrade --quiet neptune-client

     |████████████████████████████████| 245kB 3.9MB/s 
     |████████████████████████████████| 829kB 11.1MB/s 
     |████████████████████████████████| 71kB 7.1MB/s 
     |████████████████████████████████| 174kB 18.2MB/s 
     |████████████████████████████████| 133kB 13.9MB/s 
     |████████████████████████████████| 71kB 7.4MB/s 
     |████████████████████████████████| 71kB 7.0MB/s 


In [ ]:
import pandas as pd
import neptune.new as neptune
from google.colab import drive
from sklearn.preprocessing import StandardScaler
from sklearn.dummy import DummyClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split


In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
path_test = "/content/drive/MyDrive/ml/test_data.csv"
test_data = pd.read_csv(path_test, header=None)

In [ ]:
#import train dataset
path_train = "/content/drive/MyDrive/ml/train_data.csv"
train_data = pd.read_csv(path_train, header=None)

In [ ]:
#import labels
path_labels = "/content/drive/MyDrive/ml/train_labels.csv"
labels = pd.read_csv(path_labels, header=None)

In [ ]:
X, y = train_data, labels

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
test_data = scaler.transform(test_data)

In [ ]:
from sklearn.dummy import DummyClassifier
import numpy as np
strategies = ["stratified", "most_frequent", "prior", "uniform"]

for n in strategies:
  score = []
  unq = []
  dummy_clf = DummyClassifier(strategy=n)
  dummy_clf.fit(X_train, y_train)
  score_dummy=(dummy_clf.score(X_train, y_train))  
  pred_dummy = dummy_clf.predict(test_data)
  unq_dummy = np.unique(pred_dummy)
  unq.append(unq_dummy)
  score.append(score_dummy)
  print("for {} strategy score is {}, labels: {}".format(n, score, c))

for stratified strategy score is [0.8196656050955414], labels: [-1  1]
for most_frequent strategy score is [0.8996815286624203], labels: [1]
for prior strategy score is [0.8996815286624203], labels: [1]
for uniform strategy score is [0.4964171974522293], labels: [-1  1]


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, dummy_clf.predict(X_test))

array([[ 61,  62],
       [542, 573]])

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

clf = AdaBoostClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)
print(clf.score(X_train, y_train))
print(clf.score(X_test, y_test))
adabst = clf.predict(test_data)
np.unique(adabst)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


1.0
0.944264943457189


array([-1,  1])

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print(classifier.score(X_train, y_train))
np.unique(y_pred)


1.0


array([-1,  1])

In [ ]:
confusion_matrix(y_test, classifier.predict(X_test))

array([[  84,   39],
       [  28, 1087]])

In [ ]:
from sklearn.ensemble import RandomForestClassifier

regressor = RandomForestClassifier(max_depth=20, random_state=42)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print(regressor.score(X_train, y_train))
np.unique(y_pred)
y_pred


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


0.9040605095541401


array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
confusion_matrix(y_test, regressor.predict(X_test))

array([[   0,  123],
       [   0, 1115]])